#madlib!
import time
print("Hello! Welcome to my madlib! First if you could answer these couple of questions that would be awesome!")
print("If you could give me your name please!")
name = input()
print("Well hello " + name + "! Lets get started!")
print("If I can have 2 nouns")
print("1.")
noun1 = input()
print("2.")
noun2 = input()
print("Now if I can have a famous persons name")
print("1.")
famous_name = input()
print("Next up would be an adjetive")
print("1.")
adjective = input()
print("Lastly if I could have a verb please")
print("1.")
verb = input()
print("Making madlib...")    
time.sleep(10)
print("One day " + name + " entered the classroom of Mr. Cooper. You looked around the " + adjective + " classroom for a place to sit. You decided to sit next to " + famous_name + ". You hear Mr Cooper mention something about a " + noun1 + ". “Okay class. Today we are going to " + verb + " a " + noun2 + ".")
